/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sadria.view;

import com.sadria.Dao.PersonDao;
import com.sadria.Dao.SummaryDao;
import com.sadria.DaoImp.PersonDaoImp;
import com.sadria.DaoImp.SummaryDaoImp;
import com.sadria.pojo.Person;
import com.sadria.pojo.Summary;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CreateSavingACView extends javax.swing.JFrame {

    /**
     * Creates new form PersonInfoview
     */
    public CreateSavingACView() {
        initComponents();
        setLocationRelativeTo(null);
        displaySummary(sAccountNo);
        day();
        showTime();
    }
    public void day() {
        Calendar cal = new GregorianCalendar();
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);

        lblDate.setText("Date :" + day + ":" + (month + 1) + ":" + year);

    }
     void showTime() {

        new Timer(0, new ActionListener() {
           
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                 lblTime.setText(sdf.format(d));
            }
        }).start();

    }
    String fileName = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        btnUplodeImg = new javax.swing.JButton();
        jLabelACT25 = new javax.swing.JLabel();
        sAccountNo = new javax.swing.JTextField();
        jLabelACT15 = new javax.swing.JLabel();
        sFromNO = new javax.swing.JTextField();
        jLabelACT13 = new javax.swing.JLabel();
        sCardNo = new javax.swing.JTextField();
        jLabelACT10 = new javax.swing.JLabel();
        sName = new javax.swing.JTextField();
        jLabelACT5 = new javax.swing.JLabel();
        sMotherName = new javax.swing.JTextField();
        AccountType2 = new javax.swing.JComboBox<>();
        sFatherHusbendName = new javax.swing.JTextField();
        jLabelACT = new javax.swing.JLabel();
        sDateofBirth = new javax.swing.JTextField();
        jLabelACT6 = new javax.swing.JLabel();
        sNID = new javax.swing.JTextField();
        jLabelACT7 = new javax.swing.JLabel();
        comGender = new javax.swing.JComboBox<>();
        jLabelACT1 = new javax.swing.JLabel();
        sReligion = new javax.swing.JTextField();
        jLabelACT8 = new javax.swing.JLabel();
        sPresentAddress = new javax.swing.JTextField();
        jLabelACT20 = new javax.swing.JLabel();
        sParmanetAddress = new javax.swing.JTextField();
        jLabelACT12 = new javax.swing.JLabel();
        sSavingType = new javax.swing.JComboBox<>();
        jLabelACT16 = new javax.swing.JLabel();
        sAnnunity = new javax.swing.JTextField();
        jLabelACT4 = new javax.swing.JLabel();
        jLabelACT9 = new javax.swing.JLabel();
        sNomineName = new javax.swing.JTextField();
        jLabelACT11 = new javax.swing.JLabel();
        sRelations = new javax.swing.JTextField();
        jLabelACT24 = new javax.swing.JLabel();
        sShare = new javax.swing.JTextField();
        sMobilNo = new javax.swing.JTextField();
        btnExitCA1 = new javax.swing.JButton();
        btnResetCA = new javax.swing.JButton();
        btnSaveCA1 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabelACT14 = new javax.swing.JLabel();
        sAdmissionDate = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblStatement = new javax.swing.JLabel();
        lblCreateAccount1 = new javax.swing.JLabel();
        lblTranstion = new javax.swing.JLabel();
        lblInvestmentAccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDate.setBackground(new java.awt.Color(0, 102, 51));
        lblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 190, 40));

        lblTime.setBackground(new java.awt.Color(0, 102, 51));
        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));

        lblImg.setBackground(new java.awt.Color(255, 255, 255));
        lblImg.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblImg.setBorder(new javax.swing.border.MatteBorder(null));

        btnUplodeImg.setBackground(new java.awt.Color(0, 102, 51));
        btnUplodeImg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUplodeImg.setForeground(new java.awt.Color(255, 255, 255));
        btnUplodeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_image_18px.png"))); // NOI18N
        btnUplodeImg.setText("Upload Image");
        btnUplodeImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUplodeImgActionPerformed(evt);
            }
        });

        jLabelACT25.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT25.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT25.setText("Account  No");
        jLabelACT25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sAccountNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sAccountNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sAccountNo.setText("101");
        sAccountNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAccountNoActionPerformed(evt);
            }
        });

        jLabelACT15.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT15.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT15.setText("From NO");
        jLabelACT15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sFromNO.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sFromNO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sFromNO.setText("F-001");
        sFromNO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sFromNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFromNOActionPerformed(evt);
            }
        });

        jLabelACT13.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT13.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT13.setText("Card No");
        jLabelACT13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sCardNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sCardNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sCardNo.setText("C-001");
        sCardNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sCardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCardNoActionPerformed(evt);
            }
        });

        jLabelACT10.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT10.setText("Name");
        jLabelACT10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sName.setText("Md Yasin Arif");
        sName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNameActionPerformed(evt);
            }
        });

        jLabelACT5.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT5.setText("Mother's Name");
        jLabelACT5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sMotherName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sMotherName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sMotherName.setText("Yasmin Begum");
        sMotherName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sMotherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMotherNameActionPerformed(evt);
            }
        });

        AccountType2.setBackground(new java.awt.Color(0, 102, 51));
        AccountType2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AccountType2.setForeground(new java.awt.Color(255, 255, 255));
        AccountType2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Father's Name", "Husbend's Name" }));
        AccountType2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sFatherHusbendName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sFatherHusbendName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sFatherHusbendName.setText("Md Sharif Ahmed");
        sFatherHusbendName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sFatherHusbendName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFatherHusbendNameActionPerformed(evt);
            }
        });

        jLabelACT.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT.setText("Religion");
        jLabelACT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sDateofBirth.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sDateofBirth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sDateofBirth.setText("1992-11-14");
        sDateofBirth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sDateofBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sDateofBirthActionPerformed(evt);
            }
        });

        jLabelACT6.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT6.setText("NID No");
        jLabelACT6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sNID.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sNID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sNID.setText("1987456321");
        sNID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sNID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNIDActionPerformed(evt);
            }
        });

        jLabelACT7.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT7.setText("Gender");
        jLabelACT7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        comGender.setBackground(new java.awt.Color(0, 102, 51));
        comGender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comGender.setForeground(new java.awt.Color(255, 255, 255));
        comGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "FeMale" }));

        jLabelACT1.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT1.setText("Date of Birth");
        jLabelACT1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sReligion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sReligion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sReligion.setText("Islam");
        sReligion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sReligionActionPerformed(evt);
            }
        });

        jLabelACT8.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT8.setText("Present Address");
        jLabelACT8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sPresentAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sPresentAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sPresentAddress.setText("59/5/4 Shatish Sharkar Road Gandaria Dhaka-1205");
        sPresentAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sPresentAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPresentAddressActionPerformed(evt);
            }
        });

        jLabelACT20.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT20.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT20.setText("Parmanet  Address");
        jLabelACT20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sParmanetAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sParmanetAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sParmanetAddress.setText("90/A S K Dash Road Gandaria Dhaka-1204");
        sParmanetAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sParmanetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sParmanetAddressActionPerformed(evt);
            }
        });

        jLabelACT12.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT12.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT12.setText("Savings Type");
        jLabelACT12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sSavingType.setBackground(new java.awt.Color(0, 102, 51));
        sSavingType.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sSavingType.setForeground(new java.awt.Color(255, 255, 255));
        sSavingType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weekly", "Monthly", "Share", "Lone" }));
        sSavingType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelACT16.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT16.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT16.setText("Annunity");
        jLabelACT16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sAnnunity.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sAnnunity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sAnnunity.setText("500");
        sAnnunity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sAnnunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAnnunityActionPerformed(evt);
            }
        });

        jLabelACT4.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT4.setText("Mobile No");
        jLabelACT4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelACT9.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT9.setText("Nomine's Name");
        jLabelACT9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sNomineName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sNomineName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sNomineName.setText("Tawhida Sharif");
        sNomineName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sNomineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNomineNameActionPerformed(evt);
            }
        });

        jLabelACT11.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT11.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT11.setText("Relations");
        jLabelACT11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sRelations.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sRelations.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sRelations.setText("Sister");
        sRelations.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sRelations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sRelationsActionPerformed(evt);
            }
        });

        jLabelACT24.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT24.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT24.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT24.setText("Share %");
        jLabelACT24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sShare.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sShare.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sShare.setText("100");
        sShare.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sShareActionPerformed(evt);
            }
        });

        sMobilNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sMobilNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sMobilNo.setText("01676555464");
        sMobilNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sMobilNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMobilNoActionPerformed(evt);
            }
        });

        btnExitCA1.setBackground(new java.awt.Color(0, 102, 51));
        btnExitCA1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExitCA1.setForeground(new java.awt.Color(255, 255, 255));
        btnExitCA1.setText("Exit");
        btnExitCA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitCA1ActionPerformed(evt);
            }
        });

        btnResetCA.setBackground(new java.awt.Color(0, 102, 51));
        btnResetCA.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnResetCA.setForeground(new java.awt.Color(255, 255, 255));
        btnResetCA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_refresh_18px_1.png"))); // NOI18N
        btnResetCA.setText("Reset");
        btnResetCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetCAActionPerformed(evt);
            }
        });

        btnSaveCA1.setBackground(new java.awt.Color(0, 102, 51));
        btnSaveCA1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSaveCA1.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveCA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_save_18px.png"))); // NOI18N
        btnSaveCA1.setText("Save");
        btnSaveCA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCA1ActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 102, 51));
        btnSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_search_18px_4.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabelACT14.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT14.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT14.setText("Addmission Date");
        jLabelACT14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sAdmissionDate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sAdmissionDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sAdmissionDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sAdmissionDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAdmissionDateActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 102, 51));
        btnEdit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_edit_18px.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 51));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_exit_18px.png"))); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelACT25, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveCA1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetCA)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExitCA1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelACT20, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelACT8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sPresentAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                            .addComponent(sParmanetAddress))
                        .addGap(393, 393, 393))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUplodeImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(AccountType2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sFatherHusbendName))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelACT5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelACT10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sName)
                                            .addComponent(sMotherName, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabelACT7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(comGender, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabelACT, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sReligion)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelACT1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                            .addComponent(jLabelACT6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sDateofBirth)
                                            .addComponent(sNID, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelACT9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sNomineName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabelACT11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(sRelations, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabelACT24, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sShare, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelACT14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelACT15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sFromNO, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelACT13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabelACT12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(sSavingType, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelACT16, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sAnnunity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelACT4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sMobilNo, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(sCardNo))))
                        .addContainerGap(393, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUplodeImg))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelACT10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(sName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelACT5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AccountType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sFatherHusbendName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelACT7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comGender)
                                .addComponent(sDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelACT1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelACT6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelACT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sNID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelACT8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sPresentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelACT20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sParmanetAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelACT9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sNomineName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelACT11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sRelations, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelACT24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sShare, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelACT15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sFromNO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelACT13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelACT14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sAdmissionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelACT12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sSavingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelACT16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sAnnunity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sMobilNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelACT4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelACT25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSaveCA1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnResetCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3))
                    .addComponent(btnExitCA1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 169, 960, 510));

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        lblStatement.setBackground(new java.awt.Color(102, 204, 0));
        lblStatement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStatement.setForeground(new java.awt.Color(255, 255, 255));
        lblStatement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_purchase_order_18px.png"))); // NOI18N
        lblStatement.setText("Statement");
        lblStatement.setOpaque(true);
        lblStatement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatementMouseClicked(evt);
            }
        });

        lblCreateAccount1.setBackground(new java.awt.Color(0, 102, 51));
        lblCreateAccount1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreateAccount1.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateAccount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_bank_building_18px.png"))); // NOI18N
        lblCreateAccount1.setText("Saving Account");
        lblCreateAccount1.setOpaque(true);
        lblCreateAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateAccount1MouseClicked(evt);
            }
        });

        lblTranstion.setBackground(new java.awt.Color(102, 204, 0));
        lblTranstion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTranstion.setForeground(new java.awt.Color(255, 255, 255));
        lblTranstion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTranstion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_play_property_18px_1.png"))); // NOI18N
        lblTranstion.setText("Transtion");
        lblTranstion.setOpaque(true);
        lblTranstion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTranstionMouseClicked(evt);
            }
        });

        lblInvestmentAccount.setBackground(new java.awt.Color(102, 204, 0));
        lblInvestmentAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInvestmentAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblInvestmentAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvestmentAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_key_exchange_18px_2.png"))); // NOI18N
        lblInvestmentAccount.setText("Investment Account");
        lblInvestmentAccount.setOpaque(true);
        lblInvestmentAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInvestmentAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInvestmentAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
            .addComponent(lblTranstion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblStatement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblCreateAccount1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblInvestmentAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTranstion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(lblCreateAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAccountNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sAccountNoActionPerformed

    private void sFromNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFromNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sFromNOActionPerformed

    private void sCardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCardNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sCardNoActionPerformed

    private void sNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sNameActionPerformed

    private void sMotherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMotherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sMotherNameActionPerformed

    private void sFatherHusbendNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFatherHusbendNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sFatherHusbendNameActionPerformed

    private void sDateofBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sDateofBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sDateofBirthActionPerformed

    private void sNIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sNIDActionPerformed

    private void sReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sReligionActionPerformed

    private void sPresentAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPresentAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sPresentAddressActionPerformed

    private void sParmanetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sParmanetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sParmanetAddressActionPerformed

    private void sAnnunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAnnunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sAnnunityActionPerformed

    private void sNomineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNomineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sNomineNameActionPerformed

    private void sRelationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sRelationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sRelationsActionPerformed

    private void sShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sShareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sShareActionPerformed

    private void sMobilNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMobilNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sMobilNoActionPerformed

    private void btnExitCA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitCA1ActionPerformed
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "SSBBSS System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitCA1ActionPerformed

    private void btnResetCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetCAActionPerformed
        JTextField temp = null;
        for (Component c : jPanel3.getComponents()) {
            if (c.getClass().toString().contains("JTextField")) {
                temp = (JTextField) c;
                temp.setText(null);
            }
        }
        lblImg.setIcon(null);
    }//GEN-LAST:event_btnResetCAActionPerformed

    private void btnSaveCA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCA1ActionPerformed

        String accountNo = sAccountNo.getText();
        String fromNO = sFromNO.getText();
        String cardNo = sCardNo.getText();
        Date admissionDate = new java.sql.Date(System.currentTimeMillis());
        String name = sName.getText();
        String motherName = sMotherName.getText();
        String fatherHusbendName = sFatherHusbendName.getText();
        String gender = comGender.getItemAt(comGender.getSelectedIndex());
        String religion = sReligion.getText();
        String dateofBirth = sDateofBirth.getText();
        String nIDNo = sNID.getText();
        String mobileNo = sMobilNo.getText();
        String presentAddress = sPresentAddress.getText();
        String parmanetAddress = sParmanetAddress.getText();
        String savingType = sSavingType.getItemAt(sSavingType.getSelectedIndex());
        int annynity = Integer.parseInt(sAnnunity.getText());
        String nomineName = sNomineName.getText();
        String relations = sRelations.getText();
        int share = Integer.parseInt(sShare.getText());;

        try {
            Person p = new Person(accountNo, fromNO, cardNo, admissionDate, name, motherName, fatherHusbendName, gender, religion, dateofBirth, nIDNo, mobileNo, presentAddress, parmanetAddress, savingType, annynity, nomineName, relations, share);
            PersonDao pDao = new PersonDaoImp();
            pDao.save(p, new File(sourceForSave));

            Summary summary = new Summary(accountNo, name, savingType, Integer.parseInt(sAnnunity.getText().trim()), new Date(), Integer.parseInt(sAnnunity.getText().trim()), 0, Integer.parseInt(sAnnunity.getText().trim()), 1, new Date(), 0);
            SummaryDao summaryDao = new SummaryDaoImp();
            summaryDao.save(summary);
            
        } catch (Exception e) {
           
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnSaveCA1ActionPerformed
    static String sourceForSave = "";
    private void btnUplodeImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUplodeImgActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            sourceForSave = selectedFile.getAbsolutePath();

            try {
                BufferedImage img = ImageIO.read(selectedFile);
                Image newImg = img.getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);
                //  lblPhoto.setIcon(new javax.swing.ImageIcon(selectedFile.getAbsolutePath()));//Okay
                lblImg.setIcon(new javax.swing.ImageIcon(newImg, ""));

            } catch (IOException ex) {
                Logger.getLogger(CreateSavingACView.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnUplodeImgActionPerformed
    }

    public void displaySummary(JTextField acNo) {

        SummaryDao summaryDao = new SummaryDaoImp();
        Summary summary = summaryDao.getSummaryByAccontNo(acNo.getText().trim());

    }
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        PersonDao personDao = new PersonDaoImp();
        Person person = personDao.getPersoninfoByAccontNo(sAccountNo.getText().trim());

        sAdmissionDate.setText(person.getAdmissionDate() + "");
        sFromNO.setText(person.getFromNO());
        sCardNo.setText(person.getCardNo());
        sName.setText(person.getName());
        sMotherName.setText(person.getMotherName());
        sFatherHusbendName.setText(person.getFatherHusbendName());
        comGender.setSelectedItem(person.getGender());
        sDateofBirth.setText(person.getDateofBirth());
        sReligion.setText(person.getReligion());
        sNID.setText(person.getnIDNo());
        sMobilNo.setText(person.getMobileNo());
        sPresentAddress.setText(person.getPresentAddress());
        sParmanetAddress.setText(person.getParmanetAddress());
        sSavingType.setSelectedItem(person.getSavingType());
        sAnnunity.setText(person.getAnnunity() + "");
        sNomineName.setText(person.getNomineName());
        sRelations.setText(person.getRelations());
        sShare.setText(person.getShare() + "");
        lblImg.setIcon(new ImageIcon(person.getPicture()));
        displaySummary(sAccountNo);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void sAdmissionDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAdmissionDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sAdmissionDateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        String accountNo = sAccountNo.getText();
        String fromNO = sFromNO.getText();
        String cardNo = sCardNo.getText();
        Date admissionDate = new java.sql.Date(System.currentTimeMillis());
        String name = sName.getText();
        String motherName = sMotherName.getText();
        String fatherHusbendName = sFatherHusbendName.getText();
        String gender = comGender.getItemAt(comGender.getSelectedIndex());
        String religion = sReligion.getText();
        String dateofBirth = sDateofBirth.getText();
        String nIDNo = sNID.getText();
        String mobileNo = sMobilNo.getText();
        String presentAddress = sPresentAddress.getText();
        String parmanetAddress = sParmanetAddress.getText();
        String savingType = sSavingType.getItemAt(sSavingType.getSelectedIndex());
        int annynity = Integer.parseInt(sAnnunity.getText());
        String nomineName = sNomineName.getText();
        String relations = sRelations.getText();
        int share = Integer.parseInt(sShare.getText());;

        try {
            Person p = new Person(accountNo, fromNO, cardNo, admissionDate, name, motherName, fatherHusbendName, gender, religion, dateofBirth, nIDNo, mobileNo, presentAddress, parmanetAddress, savingType, annynity, nomineName, relations, share);
            PersonDao pDao = new PersonDaoImp();
            pDao.update(p, new File(sourceForSave));
          
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "SSBBSS System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lblStatementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatementMouseClicked
        this.setVisible(false);
        new InvestmentView().setVisible(false);
        new Transtionview().setVisible(false);
        new StatementView().setVisible(true);
    }//GEN-LAST:event_lblStatementMouseClicked

    private void lblCreateAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateAccount1MouseClicked

        this.setVisible(true);
        new InvestmentView().setVisible(false);
        new Transtionview().setVisible(false);
        new StatementView().setVisible(false);
    }//GEN-LAST:event_lblCreateAccount1MouseClicked

    private void lblTranstionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTranstionMouseClicked
        this.setVisible(false);
        new InvestmentView().setVisible(false);
        new Transtionview().setVisible(true);
        new StatementView().setVisible(false);
    }//GEN-LAST:event_lblTranstionMouseClicked

    private void lblInvestmentAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvestmentAccountMouseClicked
        this.setVisible(false);
        new InvestmentView().setVisible(true);
        new Transtionview().setVisible(false);
        new StatementView().setVisible(false);
    }//GEN-LAST:event_lblInvestmentAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateSavingACView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateSavingACView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateSavingACView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateSavingACView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateSavingACView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccountType2;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExitCA1;
    private javax.swing.JButton btnResetCA;
    private javax.swing.JButton btnSaveCA1;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUplodeImg;
    private javax.swing.JComboBox<String> comGender;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelACT;
    private javax.swing.JLabel jLabelACT1;
    private javax.swing.JLabel jLabelACT10;
    private javax.swing.JLabel jLabelACT11;
    private javax.swing.JLabel jLabelACT12;
    private javax.swing.JLabel jLabelACT13;
    private javax.swing.JLabel jLabelACT14;
    private javax.swing.JLabel jLabelACT15;
    private javax.swing.JLabel jLabelACT16;
    private javax.swing.JLabel jLabelACT20;
    private javax.swing.JLabel jLabelACT24;
    private javax.swing.JLabel jLabelACT25;
    private javax.swing.JLabel jLabelACT4;
    private javax.swing.JLabel jLabelACT5;
    private javax.swing.JLabel jLabelACT6;
    private javax.swing.JLabel jLabelACT7;
    private javax.swing.JLabel jLabelACT8;
    private javax.swing.JLabel jLabelACT9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCreateAccount1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblInvestmentAccount;
    private javax.swing.JLabel lblStatement;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTranstion;
    private javax.swing.JTextField sAccountNo;
    private javax.swing.JTextField sAdmissionDate;
    private javax.swing.JTextField sAnnunity;
    private javax.swing.JTextField sCardNo;
    private javax.swing.JTextField sDateofBirth;
    private javax.swing.JTextField sFatherHusbendName;
    private javax.swing.JTextField sFromNO;
    private javax.swing.JTextField sMobilNo;
    private javax.swing.JTextField sMotherName;
    private javax.swing.JTextField sNID;
    private javax.swing.JTextField sName;
    private javax.swing.JTextField sNomineName;
    private javax.swing.JTextField sParmanetAddress;
    private javax.swing.JTextField sPresentAddress;
    private javax.swing.JTextField sRelations;
    private javax.swing.JTextField sReligion;
    private javax.swing.JComboBox<String> sSavingType;
    private javax.swing.JTextField sShare;
    // End of variables declaration//GEN-END:variables
}
