/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sadria.view;

import com.sadria.Dao.InvestmentDao;
import com.sadria.Dao.InvestmentSummaryDao;
import com.sadria.Dao.PersonDao;
import com.sadria.Dao.SummaryDao;
import com.sadria.Dao.TranstionDao;
import com.sadria.DaoImp.InvestmentDaoImp;
import com.sadria.DaoImp.InvestmentSummaryDaoImp;
import com.sadria.DaoImp.PersonDaoImp;
import com.sadria.DaoImp.SummaryDaoImp;
import com.sadria.DaoImp.TranstionDaoImp;
import com.sadria.pojo.Investment;
import com.sadria.pojo.InvestmentSummary;
import com.sadria.pojo.Person;
import com.sadria.pojo.Summary;
import com.sadria.pojo.Transtion;
import static com.sadria.view.CreateSavingACView.sourceForSave;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class InvestmentView extends javax.swing.JFrame {

    /**
     * Creates new form CreateSavingACView
     */
    public InvestmentView() {
        initComponents();
        setLocationRelativeTo(null);
        displayTranstionTable();
         day();
        showTime();
    }
     public void day() {
        Calendar cal = new GregorianCalendar();
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);

        lblDate.setText("Date :" + day + ":" + (month + 1) + ":" + year);

    }

    void showTime() {

        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                lblTime.setText(sdf.format(d));
            }
        }).start();

    }
    String fileName = null;
    byte[] person_img = null;
    String accountNo;

    public void clearSummaryTable() {
        DefaultTableModel model = (DefaultTableModel) tblInvestmentA.getModel();
        model.setRowCount(0);
    }

    public void displayTranstionTable() {
        clearSummaryTable();
        InvestmentSummaryDao tDao = new InvestmentSummaryDaoImp();
        List<InvestmentSummary> list = tDao.getInvestmentSummarys();

        DefaultTableModel model = (DefaultTableModel) tblInvestmentA.getModel();
        Object[] col = new Object[11];
        for (int i = 0; i < list.size(); i++) {
            col[0] = list.get(i).getDate();
            col[1] = list.get(i).getAccountNo();
            col[2] = list.get(i).getProjectName();
            col[3] = list.get(i).getProjectLocation();
            col[4] = list.get(i).getStartDate();
            col[5] = list.get(i).getDirectortName();
            col[6] = list.get(i).getTotalInvestment();
            col[7] = list.get(i).getReturnAmount();
            col[8] = list.get(i).getBalance();
            col[9] = list.get(i).getProjectDuration();
            model.addRow(col);

        }
    }

    public void displayPersonalTranstionTable(JTextField acNo) {
        clearSummaryTable();
        InvestmentSummaryDao tDao = new InvestmentSummaryDaoImp();
        InvestmentSummary isummary = tDao.getInvestmentSummaryByAccontNo(acNo.getText().trim());

        DefaultTableModel model = (DefaultTableModel) tblInvestmentA.getModel();
        Object[] col = new Object[10];

        col[0] = isummary.getDate();
        col[1] = isummary.getAccountNo();
        col[2] = isummary.getProjectName();
        col[3] = isummary.getProjectLocation();
        col[4] = isummary.getStartDate();
        col[5] = isummary.getDirectortName();
        col[6] = isummary.getTotalInvestment();
        col[7] = isummary.getReturnAmount();
        col[8] = isummary.getBalance();
        col[9] = isummary.getProjectDuration();
        model.addRow(col);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        btnUplodeImg = new javax.swing.JButton();
        jLabelACT25 = new javax.swing.JLabel();
        txtAccountNo = new javax.swing.JTextField();
        jLabelACT10 = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        jLabelACT5 = new javax.swing.JLabel();
        txtProjectLocation = new javax.swing.JTextField();
        txtTotalInvestment = new javax.swing.JTextField();
        jLabelACT = new javax.swing.JLabel();
        txtDateofBirth = new javax.swing.JTextField();
        jLabelACT6 = new javax.swing.JLabel();
        txtNid = new javax.swing.JTextField();
        jLabelACT7 = new javax.swing.JLabel();
        comGender = new javax.swing.JComboBox<>();
        jLabelACT1 = new javax.swing.JLabel();
        txtReligion = new javax.swing.JTextField();
        jLabelACT8 = new javax.swing.JLabel();
        txtPresentAddress = new javax.swing.JTextField();
        jLabelACT20 = new javax.swing.JLabel();
        txtParmanetAddress = new javax.swing.JTextField();
        jLabelACT4 = new javax.swing.JLabel();
        txtMobilNo = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabelACT14 = new javax.swing.JLabel();
        jLabelACT17 = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        jLabelACT18 = new javax.swing.JLabel();
        txtProjectDuration = new javax.swing.JTextField();
        jLabelACT19 = new javax.swing.JLabel();
        txtDirectorName = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabelACT26 = new javax.swing.JLabel();
        txtReturn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvestmentA = new javax.swing.JTable();
        btnReturn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblStatement = new javax.swing.JLabel();
        lblCreateAccount1 = new javax.swing.JLabel();
        lblTranstion = new javax.swing.JLabel();
        lblInvestmentAccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setBackground(new java.awt.Color(0, 102, 51));
        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 120, 140, 40));

        lblDate.setBackground(new java.awt.Color(0, 102, 51));
        lblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 165));

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImg.setBackground(new java.awt.Color(255, 255, 255));
        lblImg.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblImg.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 144, 138));

        btnUplodeImg.setBackground(new java.awt.Color(0, 102, 51));
        btnUplodeImg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUplodeImg.setForeground(new java.awt.Color(255, 255, 255));
        btnUplodeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_image_18px.png"))); // NOI18N
        btnUplodeImg.setText("Upload Image");
        btnUplodeImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUplodeImgActionPerformed(evt);
            }
        });
        jPanel3.add(btnUplodeImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 144, -1));

        jLabelACT25.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT25.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT25.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT25.setText("Account  No");
        jLabelACT25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT25, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 250, 140, 30));

        txtAccountNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtAccountNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccountNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNoActionPerformed(evt);
            }
        });
        jPanel3.add(txtAccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 291, 144, 30));

        jLabelACT10.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT10.setText("Project Name");
        jLabelACT10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT10, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 11, 192, 30));

        txtProjectName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtProjectName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProjectName.setText("Fisharing");
        txtProjectName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtProjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtProjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 11, 557, 30));

        jLabelACT5.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT5.setText("Project Location");
        jLabelACT5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 51, 192, 30));

        txtProjectLocation.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtProjectLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProjectLocation.setText("Aminpara,KaraniGong,Dhaka");
        txtProjectLocation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtProjectLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectLocationActionPerformed(evt);
            }
        });
        jPanel3.add(txtProjectLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 51, 557, 30));

        txtTotalInvestment.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtTotalInvestment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalInvestment.setText("1000");
        txtTotalInvestment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTotalInvestment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalInvestmentActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotalInvestment, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 91, 94, 30));

        jLabelACT.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT.setText("Religion");
        jLabelACT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 121, 30));

        txtDateofBirth.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtDateofBirth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDateofBirth.setText("1992-11-11");
        txtDateofBirth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDateofBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateofBirthActionPerformed(evt);
            }
        });
        jPanel3.add(txtDateofBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 110, 30));

        jLabelACT6.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT6.setText("NID No");
        jLabelACT6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 121, 30));

        txtNid.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtNid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNid.setText("4545796331235");
        txtNid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtNid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNidActionPerformed(evt);
            }
        });
        jPanel3.add(txtNid, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 270, 30));

        jLabelACT7.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT7.setText("Gender");
        jLabelACT7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 168, 192, 30));

        comGender.setBackground(new java.awt.Color(0, 102, 51));
        comGender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comGender.setForeground(new java.awt.Color(255, 255, 255));
        comGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "FeMale" }));
        jPanel3.add(comGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 91, -1));

        jLabelACT1.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT1.setText("Date of Birth");
        jLabelACT1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 130, 30));

        txtReligion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtReligion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReligion.setText("Islam");
        txtReligion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReligionActionPerformed(evt);
            }
        });
        jPanel3.add(txtReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 168, 49, 30));

        jLabelACT8.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT8.setText("Present Address");
        jLabelACT8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 250, 194, 30));

        txtPresentAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPresentAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPresentAddress.setText("59/5/4 Shatish Sharkar Road Gandaria Dhaka-1205");
        txtPresentAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtPresentAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresentAddressActionPerformed(evt);
            }
        });
        jPanel3.add(txtPresentAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 250, 570, 30));

        jLabelACT20.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT20.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT20.setText("Parmanet  Address");
        jLabelACT20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT20, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 291, 194, 30));

        txtParmanetAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtParmanetAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtParmanetAddress.setText("90/A S K Dash Road Gandaria Dhaka-1204");
        txtParmanetAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtParmanetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParmanetAddressActionPerformed(evt);
            }
        });
        jPanel3.add(txtParmanetAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 291, 570, 30));

        jLabelACT4.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT4.setText("Mobile No");
        jLabelACT4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 209, 192, 30));

        txtMobilNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtMobilNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMobilNo.setText("01676555764");
        txtMobilNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtMobilNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobilNoActionPerformed(evt);
            }
        });
        jPanel3.add(txtMobilNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 150, 30));

        btnExit.setBackground(new java.awt.Color(0, 102, 51));
        btnExit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_exit_18px.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 90, 30));

        btnUpdate.setBackground(new java.awt.Color(0, 102, 51));
        btnUpdate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_edit_18px.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, 30));

        btnSave.setBackground(new java.awt.Color(0, 102, 51));
        btnSave.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_save_18px.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 100, 30));

        jLabelACT14.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT14.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT14.setText("Invested Amount");
        jLabelACT14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT14, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 91, 192, 30));

        jLabelACT17.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT17.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT17.setText("Start Date ");
        jLabelACT17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT17, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 91, 127, 30));

        txtStartDate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtStartDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStartDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });
        jPanel3.add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 91, 110, 30));

        jLabelACT18.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT18.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT18.setText("Project Duration");
        jLabelACT18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT18, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 91, -1, 30));

        txtProjectDuration.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtProjectDuration.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProjectDuration.setText("5");
        txtProjectDuration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtProjectDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectDurationActionPerformed(evt);
            }
        });
        jPanel3.add(txtProjectDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 93, 30, -1));

        jLabelACT19.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT19.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT19.setText("Director Name");
        jLabelACT19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT19, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 132, 192, 30));

        txtDirectorName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtDirectorName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDirectorName.setText("Md Yasin Arif Sohan");
        txtDirectorName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtDirectorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectorNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtDirectorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 132, 557, 30));

        btnReset.setBackground(new java.awt.Color(0, 102, 51));
        btnReset.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_refresh_18px_1.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel3.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 110, 30));

        btnSearch.setBackground(new java.awt.Color(0, 102, 51));
        btnSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 341, 144, 30));

        jLabelACT26.setBackground(new java.awt.Color(0, 102, 51));
        jLabelACT26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelACT26.setForeground(new java.awt.Color(255, 255, 255));
        jLabelACT26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelACT26.setText("Amount");
        jLabelACT26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelACT26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabelACT26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 428, 140, 30));

        txtReturn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtReturn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReturn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReturnActionPerformed(evt);
            }
        });
        jPanel3.add(txtReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 428, 173, 30));

        tblInvestmentA.setBackground(new java.awt.Color(204, 255, 204));
        tblInvestmentA.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblInvestmentA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblInvestmentA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Account No", "Project Name", "Project Location", "Start Date", "Director Name", "Total Investment", "Return", "Balance", "Project Duration"
            }
        ));
        jScrollPane1.setViewportView(tblInvestmentA);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 332, 790, 78));

        btnReturn.setBackground(new java.awt.Color(0, 102, 51));
        btnReturn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel3.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 170, 960, 510));

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        lblStatement.setBackground(new java.awt.Color(102, 204, 0));
        lblStatement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStatement.setForeground(new java.awt.Color(255, 255, 255));
        lblStatement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_purchase_order_18px.png"))); // NOI18N
        lblStatement.setText("Statement");
        lblStatement.setOpaque(true);
        lblStatement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatementMouseClicked(evt);
            }
        });

        lblCreateAccount1.setBackground(new java.awt.Color(102, 204, 0));
        lblCreateAccount1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreateAccount1.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateAccount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_bank_building_18px.png"))); // NOI18N
        lblCreateAccount1.setText("Saving Account");
        lblCreateAccount1.setOpaque(true);
        lblCreateAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateAccount1MouseClicked(evt);
            }
        });

        lblTranstion.setBackground(new java.awt.Color(102, 204, 0));
        lblTranstion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTranstion.setForeground(new java.awt.Color(255, 255, 255));
        lblTranstion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTranstion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_play_property_18px_1.png"))); // NOI18N
        lblTranstion.setText("Transtion");
        lblTranstion.setOpaque(true);
        lblTranstion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTranstionMouseClicked(evt);
            }
        });

        lblInvestmentAccount.setBackground(new java.awt.Color(0, 102, 51));
        lblInvestmentAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInvestmentAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblInvestmentAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvestmentAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_key_exchange_18px_2.png"))); // NOI18N
        lblInvestmentAccount.setText("Investment Account");
        lblInvestmentAccount.setOpaque(true);
        lblInvestmentAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInvestmentAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInvestmentAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
            .addComponent(lblTranstion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblStatement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblCreateAccount1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblInvestmentAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTranstion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(lblCreateAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static String sourceForSave = "";
    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        InvestmentDao iDao = new InvestmentDaoImp();
        accountNo = txtAccountNo.getText();
        InvestmentSummaryDao isammaryDao = new InvestmentSummaryDaoImp();
        InvestmentSummary isammary = isammaryDao.getInvestmentSummaryByAccontNo(accountNo);
        if (isammary.getAccountNo() != null) {
            double totalReturn = isammary.getReturnAmount() + Double.parseDouble(txtReturn.getText());
            double balance = isammary.getTotalInvestment() - +(isammary.getReturnAmount() + Double.parseDouble(txtReturn.getText()));

            InvestmentSummary summaryUp = new InvestmentSummary(isammary.getAccountNo(), isammary.getTotalInvestment(), totalReturn, balance);
            isammaryDao.updateForDeposit(summaryUp);
            displayPersonalTranstionTable(txtAccountNo);
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void txtReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReturnActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        InvestmentDao iDao = new InvestmentDaoImp();
        Investment investment = iDao.getInvestmentinfoByAccontNo(txtAccountNo.getText().trim());

        txtProjectName.setText(investment.getProjectName());
        txtProjectLocation.setText(investment.getProjectLocation());
        txtTotalInvestment.setText(investment.getTotalInvestment() + "");
        txtStartDate.setText(investment.getStartDate() + "");
        txtProjectDuration.setText(investment.getProjectDuration() + "");
        txtDirectorName.setText(investment.getDirectortName());
        comGender.getItemAt(comGender.getSelectedIndex());
        txtReligion.setText(investment.getReligion());;
        txtDateofBirth.setText(investment.getDateofBirth());
        txtNid.setText(investment.getnIDNo());
        txtMobilNo.setText(investment.getMobileNo());
        txtPresentAddress.setText(investment.getPresentAddress());
        txtParmanetAddress.setText(investment.getParmanetAddress());
        lblImg.setIcon(new ImageIcon(investment.getPicture()));
        displayPersonalTranstionTable(txtAccountNo);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        JTextField temp = null;
        for (Component c : jPanel3.getComponents()) {
            if (c.getClass().toString().contains("JTextField")) {
                temp = (JTextField) c;
                temp.setText(null);
            }
        }
        DefaultTableModel model = (DefaultTableModel) tblInvestmentA.getModel();
        model.setRowCount(0);
        lblImg.setIcon(null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtDirectorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectorNameActionPerformed

    private void txtProjectDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectDurationActionPerformed

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        InvestmentDao iDao = new InvestmentDaoImp();
        accountNo = txtAccountNo.getText();
        String projectName = txtProjectName.getText();
        String projectLocation = txtProjectLocation.getText();
        Double totalInvestment = Double.parseDouble(txtTotalInvestment.getText());
        Date txtStartDate = new java.sql.Date(System.currentTimeMillis());
        int projectDuration = Integer.parseInt(txtProjectDuration.getText());
        String directorName = txtDirectorName.getText();
        String gender = comGender.getItemAt(comGender.getSelectedIndex());
        String religion = txtReligion.getText();
        String dateofBirth = txtDateofBirth.getText();
        String nIDNo = txtNid.getText();
        String mobileNo = txtMobilNo.getText();
        String presentAddress = txtPresentAddress.getText();
        String parmanetAddress = txtParmanetAddress.getText();

        try {
            Investment i = new Investment(accountNo, projectName, projectLocation, totalInvestment, txtStartDate, projectDuration, directorName, gender, religion, dateofBirth, nIDNo, mobileNo, presentAddress, parmanetAddress);
            iDao.save(i, new File(sourceForSave));

            InvestmentSummaryDao isummaryDao = new InvestmentSummaryDaoImp();

            InvestmentSummary investmentSummary = new InvestmentSummary(new Date(), accountNo, projectName, projectLocation, new Date(), directorName, totalInvestment, 0.0, totalInvestment, projectDuration);
            isummaryDao.save(investmentSummary);
            displayTranstionTable();
           
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        InvestmentDao iDao = new InvestmentDaoImp();
        accountNo = txtAccountNo.getText();
        String projectName = txtProjectName.getText();
        String projectLocation = txtProjectLocation.getText();
        Double totalInvestment = Double.parseDouble(txtTotalInvestment.getText());
        Date txtStartDate = new java.sql.Date(System.currentTimeMillis());
        int projectDuration = Integer.parseInt(txtProjectDuration.getText());
        String directorName = txtDirectorName.getText();
        String gender = comGender.getItemAt(comGender.getSelectedIndex());
        String religion = txtReligion.getText();
        String dateofBirth = txtDateofBirth.getText();
        String nIDNo = txtNid.getText();
        String mobileNo = txtMobilNo.getText();
        String presentAddress = txtPresentAddress.getText();
        String parmanetAddress = txtParmanetAddress.getText();

        try {
            Investment i = new Investment(accountNo, projectName, projectLocation, totalInvestment, txtStartDate, projectDuration, directorName, gender, religion, dateofBirth, nIDNo, mobileNo, presentAddress, parmanetAddress);
            iDao.update(i, new File(sourceForSave));
           
        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "SSBBSS System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtMobilNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobilNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobilNoActionPerformed

    private void txtParmanetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParmanetAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParmanetAddressActionPerformed

    private void txtPresentAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresentAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresentAddressActionPerformed

    private void txtReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReligionActionPerformed

    private void txtNidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNidActionPerformed

    private void txtDateofBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateofBirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateofBirthActionPerformed

    private void txtTotalInvestmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalInvestmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalInvestmentActionPerformed

    private void txtProjectLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectLocationActionPerformed

    private void txtProjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectNameActionPerformed

    private void txtAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNoActionPerformed

    private void btnUplodeImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUplodeImgActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            sourceForSave = selectedFile.getAbsolutePath();

            try {
                BufferedImage img = ImageIO.read(selectedFile);
                Image newImg = img.getScaledInstance(lblImg.getWidth(), lblImg.getHeight(), Image.SCALE_SMOOTH);

                lblImg.setIcon(new javax.swing.ImageIcon(newImg, ""));

            } catch (IOException ex) {
                Logger.getLogger(CreateSavingACView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUplodeImgActionPerformed

    private void lblStatementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatementMouseClicked
        this.setVisible(false);
        new CreateSavingACView().setVisible(false);
        new Transtionview().setVisible(false);
        new StatementView().setVisible(true);
    }//GEN-LAST:event_lblStatementMouseClicked

    private void lblCreateAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateAccount1MouseClicked

        this.setVisible(false);
        new CreateSavingACView().setVisible(true);
        new Transtionview().setVisible(false);
        new StatementView().setVisible(false);
    }//GEN-LAST:event_lblCreateAccount1MouseClicked

    private void lblTranstionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTranstionMouseClicked
        this.setVisible(false);
        new CreateSavingACView().setVisible(false);
        new Transtionview().setVisible(true);
        new StatementView().setVisible(false);
    }//GEN-LAST:event_lblTranstionMouseClicked

    private void lblInvestmentAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvestmentAccountMouseClicked
        this.setVisible(true);
        new CreateSavingACView().setVisible(false);
        new Transtionview().setVisible(false);
        new StatementView().setVisible(false);
    }//GEN-LAST:event_lblInvestmentAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvestmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvestmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvestmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvestmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvestmentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUplodeImg;
    private javax.swing.JComboBox<String> comGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelACT;
    private javax.swing.JLabel jLabelACT1;
    private javax.swing.JLabel jLabelACT10;
    private javax.swing.JLabel jLabelACT14;
    private javax.swing.JLabel jLabelACT17;
    private javax.swing.JLabel jLabelACT18;
    private javax.swing.JLabel jLabelACT19;
    private javax.swing.JLabel jLabelACT20;
    private javax.swing.JLabel jLabelACT25;
    private javax.swing.JLabel jLabelACT26;
    private javax.swing.JLabel jLabelACT4;
    private javax.swing.JLabel jLabelACT5;
    private javax.swing.JLabel jLabelACT6;
    private javax.swing.JLabel jLabelACT7;
    private javax.swing.JLabel jLabelACT8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateAccount1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblInvestmentAccount;
    private javax.swing.JLabel lblStatement;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTranstion;
    private javax.swing.JTable tblInvestmentA;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextField txtDateofBirth;
    private javax.swing.JTextField txtDirectorName;
    private javax.swing.JTextField txtMobilNo;
    private javax.swing.JTextField txtNid;
    private javax.swing.JTextField txtParmanetAddress;
    private javax.swing.JTextField txtPresentAddress;
    private javax.swing.JTextField txtProjectDuration;
    private javax.swing.JTextField txtProjectLocation;
    private javax.swing.JTextField txtProjectName;
    private javax.swing.JTextField txtReligion;
    private javax.swing.JTextField txtReturn;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTotalInvestment;
    // End of variables declaration//GEN-END:variables
}
