/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sadria.view;

import com.sadria.Dao.PersonDao;
import com.sadria.Dao.SummaryDao;
import com.sadria.Dao.TranstionDao;
import com.sadria.DaoImp.PersonDaoImp;
import com.sadria.DaoImp.SummaryDaoImp;
import com.sadria.DaoImp.TranstionDaoImp;
import com.sadria.pojo.Person;
import com.sadria.pojo.Summary;
import com.sadria.pojo.Transtion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class StatementView extends javax.swing.JFrame {

    /**
     * Creates new form StatementView
     */
    public StatementView() {
        initComponents();
        setLocationRelativeTo(null);
        day();
        showTime();

    }

    public void day() {
        Calendar cal = new GregorianCalendar();
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);

        lblDate.setText("Date :" + day + ":" + (month + 1) + ":" + year);

    }

    void showTime() {

        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                lblTime.setText(sdf.format(d));
            }
        }).start();

    }

    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tblTranscation.getModel();
        model.setRowCount(0);
    }

    public void displayTranstionTable(JTextField acNo) {
        clearTable();
        TranstionDao tDao = new TranstionDaoImp();

        List<Transtion> list = tDao.getTranstion(acNo.getText());
        DefaultTableModel model = (DefaultTableModel) tblTranscation.getModel();
        Object[] col = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            col[0] = list.get(i).getId();
            col[1] = list.get(i).getDate();
            col[2] = list.get(i).getAccountNo();
            col[3] = list.get(i).getName();
            col[4] = list.get(i).getSlipNo();
            col[5] = list.get(i).getDeposit();
            col[6] = list.get(i).getWithdraw();
            model.addRow(col);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panalstatement = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAccountNo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaStatement = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTranscation = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblStatement = new javax.swing.JLabel();
        lblCreateAccount1 = new javax.swing.JLabel();
        lblTranstion = new javax.swing.JLabel();
        lblInvestmentAccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setBackground(new java.awt.Color(0, 102, 51));
        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 120, 140, 40));

        lblDate.setBackground(new java.awt.Color(0, 102, 51));
        lblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 190, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/logo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 170));

        panalstatement.setBackground(new java.awt.Color(0, 102, 51));

        jLabel3.setBackground(new java.awt.Color(0, 102, 51));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Account No");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtAccountNo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtAccountNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccountNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtAccountNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountNoActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 102, 51));
        btnSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_search_18px_4.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(0, 102, 51));
        btnPrint.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_print_18px.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 102, 51));
        btnClear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_clear_formatting_18px.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtAreaStatement.setColumns(20);
        txtAreaStatement.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtAreaStatement.setRows(5);
        jScrollPane2.setViewportView(txtAreaStatement);

        tblTranscation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Date", "Account NO", "Name", "SlipNo", "Deposit", "Withdraw"
            }
        ));
        jScrollPane3.setViewportView(tblTranscation);

        javax.swing.GroupLayout panalstatementLayout = new javax.swing.GroupLayout(panalstatement);
        panalstatement.setLayout(panalstatementLayout);
        panalstatementLayout.setHorizontalGroup(
            panalstatementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalstatementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panalstatementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panalstatementLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnPrint)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panalstatementLayout.setVerticalGroup(
            panalstatementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalstatementLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panalstatementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panalstatement, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 176, 960, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        lblStatement.setBackground(new java.awt.Color(0, 102, 51));
        lblStatement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStatement.setForeground(new java.awt.Color(255, 255, 255));
        lblStatement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_purchase_order_18px.png"))); // NOI18N
        lblStatement.setText("Statement");
        lblStatement.setOpaque(true);
        lblStatement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatementMouseClicked(evt);
            }
        });

        lblCreateAccount1.setBackground(new java.awt.Color(102, 204, 0));
        lblCreateAccount1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCreateAccount1.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateAccount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateAccount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_bank_building_18px.png"))); // NOI18N
        lblCreateAccount1.setText("Saving Account");
        lblCreateAccount1.setOpaque(true);
        lblCreateAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateAccount1MouseClicked(evt);
            }
        });

        lblTranstion.setBackground(new java.awt.Color(102, 204, 0));
        lblTranstion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTranstion.setForeground(new java.awt.Color(255, 255, 255));
        lblTranstion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTranstion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_play_property_18px_1.png"))); // NOI18N
        lblTranstion.setText("Transtion");
        lblTranstion.setOpaque(true);
        lblTranstion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTranstionMouseClicked(evt);
            }
        });

        lblInvestmentAccount.setBackground(new java.awt.Color(102, 204, 0));
        lblInvestmentAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblInvestmentAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblInvestmentAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInvestmentAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sadria/img/icons8_key_exchange_18px_2.png"))); // NOI18N
        lblInvestmentAccount.setText("Investment Account");
        lblInvestmentAccount.setOpaque(true);
        lblInvestmentAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInvestmentAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblInvestmentAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
            .addComponent(lblTranstion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblStatement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblCreateAccount1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblInvestmentAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTranstion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(lblCreateAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(483, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 176, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccountNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountNoActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        PersonDao personDao = new PersonDaoImp();
        Person person = personDao.getPersoninfoByAccontNo(txtAccountNo.getText().trim());
        SummaryDao summaryDao = new SummaryDaoImp();
        Summary summary = summaryDao.getSummaryByAccontNo(txtAccountNo.getText().trim());
        txtAreaStatement.setText(txtAreaStatement.getText() + "SADRIA SOCITY BISUDHA BISAWAN SOMOBAY SOMITY\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "***********************************************\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "PERSONAL INFORMATION\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Name                :" + person.getName() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Mother's Name       :" + person.getMotherName() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Father/Husbend Name :" + person.getFatherHusbendName() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Gender              :" + person.getGender() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Religion            :" + person.getReligion() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Date of Birth       :" + person.getDateofBirth() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "NID No              :" + person.getnIDNo() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Mobile No           :" + person.getMobileNo() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Present Address     :" + person.getPresentAddress() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Parmanet Address    :" + person.getParmanetAddress() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Nomine Name         :" + person.getNomineName() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Relations           : " + person.getRelations() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "% of Share          :" + person.getShare() + "\n\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "ACCOUNTS DETAILS\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Account No          :" + person.getAccountNo() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "From NO             :" + person.getFromNO() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Card No             :" + person.getCardNo() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Admission Date      :" + person.getAdmissionDate() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Account Type        :" + person.getSavingType() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Annunity            :" + person.getAnnunity() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Total Deposit       :" + summary.getTotalDeposit() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Total Withdraw      :" + summary.getTotalWithdraw() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Balance             :" + summary.getBalance() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Installment No      :" + summary.getInstallmentNo() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Coverv Date         :" + summary.getCoverDate() + "\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "Due                 :" + summary.getDue() + "\n\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "                        -----------------\n");
        txtAreaStatement.setText(txtAreaStatement.getText() + "                           signature");
        displayTranstionTable(txtAccountNo);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            txtAreaStatement.print();
            tblTranscation.print();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void lblStatementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatementMouseClicked
        this.setVisible(true);
        new InvestmentView().setVisible(false);
        new Transtionview().setVisible(false);
        new CreateSavingACView().setVisible(false);
    }//GEN-LAST:event_lblStatementMouseClicked

    private void lblCreateAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateAccount1MouseClicked

        this.setVisible(false);
        new CreateSavingACView().setVisible(true);
        new InvestmentView().setVisible(false);
        new Transtionview().setVisible(false);
    }//GEN-LAST:event_lblCreateAccount1MouseClicked

    private void lblTranstionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTranstionMouseClicked
        this.setVisible(false);
        new CreateSavingACView().setVisible(false);
        new Transtionview().setVisible(true);
        new InvestmentView().setVisible(false);
    }//GEN-LAST:event_lblTranstionMouseClicked

    private void lblInvestmentAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInvestmentAccountMouseClicked
        this.setVisible(false);
        new CreateSavingACView().setVisible(false);
        new Transtionview().setVisible(false);
        new InvestmentView().setVisible(true);
    }//GEN-LAST:event_lblInvestmentAccountMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtAccountNo.setText("");
        txtAreaStatement.setText("");
        DefaultTableModel model = (DefaultTableModel) tblTranscation.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatementView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCreateAccount1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblInvestmentAccount;
    private javax.swing.JLabel lblStatement;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTranstion;
    private javax.swing.JPanel panalstatement;
    private javax.swing.JTable tblTranscation;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextArea txtAreaStatement;
    // End of variables declaration//GEN-END:variables
}
